### ISSUE TITLE
I tried to build this project on windows, but it failed

### ISSUE THREAD

**Issue by ShiningMan123** [amadeok/Epdiy-Eink-PC-monitor#5]
I tried to build this project on windows, but it failed

**Comment by ShiningMan123** [comment]
![5c89b0c086a9588314c39c8e2ebcf9f](https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/e337276b-7425-4c3e-ac0e-265e49a5f2d1)

**Comment by amadeok** [comment]
> ![5c89b0c086a9588314c39c8e2ebcf9f](https://user-images.githubusercontent.com/122499079/284498569-e337276b-7425-4c3e-ac0e-265e49a5f2d1.png)

hi, post the full output of the console

**Comment by ShiningMan123** [comment]
![32b8794d61fa68e6c77ab55932bff19](https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/0a7d5ebf-0004-4c67-91ab-38d9c88743bf)

**Comment by amadeok** [comment]
> ![32b8794d61fa68e6c77ab55932bff19](https://user-images.githubusercontent.com/122499079/284752913-0a7d5ebf-0004-4c67-91ab-38d9c88743bf.png)

did you  build the base epd driver succesfully ? were you able to run the examples in the epdiy repository? what version of epdiy are you running and what board revision are you using?

**Comment by ShiningMan123** [comment]
I could have built those examples. I used the epdiy-v5 version

**Comment by amadeok** [comment]
> I could have built those examples. I used the epdiy-v5 version

Hello
In fact it seems updates were made to the epdiy driver that cause our application to not build.
I'll try to contact the maker of the epdiy board to see exactly how to better update our application.

But you can still use our application by compiling using the version v5 of the firmware. We made some changes to the code to work with branch v5 of the epdiy repository. 
I also updated the instructions so you can just follow the instructions again, the only change in the instructions is that instead of cloning main branch of the epdiy repository you have to clone branch v5.
So, instead of this 
git clone https://github.com/vroland/epdiy
you do this 
git clone -b v5 https://github.com/vroland/epdiy

**Comment by ShiningMan123** [comment]
<img width="1009" alt="ea316c8294061f5874996dba703f76d" src="https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/04cf5289-3d53-4d61-9bd1-7619d338b99f">
hi, I have a problem with this place. Can you help me

**Comment by ShiningMan123** [comment]
C:\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app>python screen_capture.py example_display.conf
Dpi awareness set correctly
Invalid dither method selected, setting monochrome
No Input pipe, trying again in a sec
esp32_ip_address: 192.168.2.154
display id: 0
refresh_every_x_frames: 100
do_full_refresh: 30
framebuffer_cycles: 4
enable_skipping: 0
epd_skip_threshold: 75
esp32_multithread: 0
framebuffer_cycles_2: 4
framebuffer_cycles_2_threshold: 76
selective_compression: 90
nb_chunks: 1
nb_draws: 1
draw_white_first: 0
mode: 0
draw_rmt_times:  250  100  250  250
wifi enabled
pipe Python capture ID 0: Input pipe opened
fd1 is ok

Initialising Winsock...Python capture ID 0: Output pipe opened
WSAD Initialised.
current working directory is: C:\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app
Connected to esp wifi

C++ ID 0 mirroring started
color 1.0, contrast  2.0  brightness 1.0, sharpness 1.0,  grey_to_monochrome_threshold 200
Display ID: 0, capture took 9811ms
Traceback (most recent call last):
  File "C:\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py", line 237, in <module>
    main_task(ctx)
  File "C:\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py", line 132, in main_task
    elif windows: ret2 = win32file.ReadFile(fd1, 1)
pywintypes.error: (109, 'ReadFile', '管道已结束。')

**Comment by ShiningMan123** [comment]
My system version number is windows 10 21h2

**Comment by amadeok** [comment]
> <img alt="ea316c8294061f5874996dba703f76d" width="1009" src="https://private-user-images.githubusercontent.com/122499079/286837612-04cf5289-3d53-4d61-9bd1-7619d338b99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTMyMjMsIm5iZiI6MTcwMTUxMjkyMywicGF0aCI6Ii8xMjI0OTkwNzkvMjg2ODM3NjEyLTA0Y2Y1Mjg5LTNkNTMtNGQ2MS05YmQxLTc2MTlkMzM4Yjk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMDI4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzE2ZDNiNDNkZWUwYzY5OTdiNDE2ODc5OTVjMGZiNjBiNjdmMThlZDMxYTA0NDg3MzU0NTNkMzVjZTc0YTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sw0TF5GvmCgbAYy3jmk7eN3LujmZJUZwb1eJZ2rPXM8"> hi, I have a problem with this place. Can you help me


Hello
It seems you confused the include directory, 
There are two include directories, one for the board application ( epdiy\examples\Epdiy-Eink-PC-monitor\pc_monitor\include )  and one for the pc application ( epdiy\examples\Epdiy-Eink-PC-monitor\pc_monitor\pc_host_app\include )
You have to use the include folder of the pc application to compile the pc application

In your case, it should be like this :
 g++ main.cpp  generate_eink_framebuffer.cpp rle_compression.cpp  utils.cpp -static   -o   process_capture.exe   -I "C:\Users\goodisplay\Desktop\epdiy\examples\Epdiy-Eink-PC-monitor\pc_monitor\pc_host_app\include"  -lws2_32
Check if there are any typing errors.
The python script should work after you are able to compile the pc executable

**Comment by ShiningMan123** [comment]
> C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app>python screen_capture.py example_display.conf 正确设置 Dpi 感知 选择的抖动方法无效，设置单色 无输入管道，一秒钟后重试 esp32_ip_address：192.168.2.154 显示 ID：0 refresh_every_x_frames：100 do_full_refresh：30 framebuffer_cycles：4 enable_skipping： 0 epd_skip_threshold：75 esp32_multithread：0 framebuffer_cycles_2：4 framebuffer_cycles_2_threshold：76 selective_compression：90 nb_chunks：1 nb_draws：1 draw_white_first：0 模式：0 draw_rmt_times：250 100 250 250 启用 wifi 的管道 Python 捕获 ID 0：输入管道打开 fd1 正常
> 
> 正在初始化 Winsock...Python 捕获 ID 0：输出管道已打开 WSAD 已初始化。当前工作目录为：C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app 连接到 esp wifi
> 
> C++ ID 0 镜像开始 颜色 1.0，对比度 2.0 亮度 1.0，锐度 1.0，grey_to_monochrome_threshold 200 显示 ID：0，捕获耗时 9811 毫秒 回溯（最近一次调用最后一次）： 文件“C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py”，第 237 行，在 main_task（ctx） 中 文件“C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py”， 第 132 行，在 main_task ELIF 窗口中：RET2 = Win32File。ReadFile（fd1， 1） pywintypes.error： （109， 'ReadFile'， '管道已结束。')

How to solve this problem

**Comment by amadeok** [comment]
> > C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app>python screen_capture.py example_display.conf 正确设置 Dpi 感知 选择的抖动方法无效，设置单色 无输入管道，一秒钟后重试 esp32_ip_address：192.168.2.154 显示 ID：0 refresh_every_x_frames：100 do_full_refresh：30 framebuffer_cycles：4 enable_skipping： 0 epd_skip_threshold：75 esp32_multithread：0 framebuffer_cycles_2：4 framebuffer_cycles_2_threshold：76 selective_compression：90 nb_chunks：1 nb_draws：1 draw_white_first：0 模式：0 draw_rmt_times：250 100 250 250 启用 wifi 的管道 Python 捕获 ID 0：输入管道打开 fd1 正常
> > 正在初始化 Winsock...Python 捕获 ID 0：输出管道已打开 WSAD 已初始化。当前工作目录为：C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app 连接到 esp wifi
> > C++ ID 0 镜像开始 颜色 1.0，对比度 2.0 亮度 1.0，锐度 1.0，grey_to_monochrome_threshold 200 显示 ID：0，捕获耗时 9811 毫秒 回溯（最近一次调用最后一次）： 文件“C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py”，第 237 行，在 main_task（ctx） 中 文件“C：\Users\goodisplay\Desktop\epdiy\examples\pc_monitor\pc_host_app\screen_capture.py”， 第 132 行，在 main_task ELIF 窗口中：RET2 = Win32File。ReadFile（fd1， 1） pywintypes.error： （109， 'ReadFile'， '管道已结束。')
> 
> How to solve this problem

did you compile dither_.dlll file as well ? 
`g++ dither_.cpp invert_.cpp -o dither_.dll -shared -fPIC
`

please try to use this executable instead of the one you compiled, maybe your gcc compiler isn't working properly
https://github.com/amadeok/Epdiy-Eink-PC-monitor/releases/download/0.061/windows_binaries.zip
download it, extract it, and replace the ones you have with these ones

**Comment by ShiningMan123** [comment]
<img width="509" alt="3157558c2a842b0b9aae33b918cb9a6" src="https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/f429ee8b-3cf0-4328-9cd1-710ae6cb1a05">
Hello, is this state correct? I use a 13.3-inch e-paper, I can hear the sound of the screen ic, but there is no display on the screen

**Comment by ShiningMan123** [comment]
<img width="743" alt="7c968eae7c647d26db7fd86d6efaae7" src="https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/3555b4cd-a086-44bb-9464-a0103b32d496">
<img width="653" alt="c9e5113f22a856dd72d956d3a483c67" src="https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/56e2a169-bb2d-4e03-86a0-6d2c2de667e5">
<img width="431" alt="6ff01aef3af5c6afbf0bbd3aa47acaa" src="https://github.com/amadeok/Epdiy-Eink-PC-monitor/assets/122499079/32a977c4-844c-4303-9546-7a1315f56612">

**Comment by ShiningMan123** [comment]
My screen didn't react at all

**Comment by amadeok** [comment]
> My screen didn't react at all

The display doesn't react in any way? not even the initial screen refresh where it goes black and white a few times?
The output from the console that you posted seems normal, but the times per frame are way too high, this could be because the wifi router is too far away from the board. Ideally the router should be in the same room as the board. I reccomend using the wifi hotspot on your phone, and connect both the pc and board to the wifi hotspot.
you can try to flash this binary to the board 
https://github.com/amadeok/Epdiy-Eink-PC-monitor/releases/download/Board-binary-V5-ED133UT2/Epdiy.board.binary-V5-ED133UT2.zip
download, extract, and flash it like this  
`idf.py  flash   "firmware.bin"
`
